contentful/contentful_middleman

CHANGELOG.md
lib/contentful_middleman/mappers/base.rb

Related issue https://github.com/contentful-labs/contentful_middleman/issues/12

Map location fields

---

lib/contentful_middleman/commands/contentful.rb

Fix typo in require

---

CHANGELOG.md
lib/contentful_middleman/commands/context.rb
lib/contentful_middleman/mappers/base.rb

Before this fix the import process will crash when trying to map an entry which had a field
containing an array of symbols
Related https://github.com/contentful-labs/contentful_middleman/issues/17

Import entries with array fields with elements other thank links

---

README.md

Related https://github.com/contentful-labs/contentful_middleman/issues/15

Clarify where to look for query parameters in contentful.rb

---

README.md
examples/mappers/backref.rb
lib/contentful_middleman/import_task.rb
lib/contentful_middleman/mappers/base.rb

Added a back-reference mapper the the mappers directory.

Back-reference mapper

---

lib/contentful_middleman/commands/contentful.rb

Set a custom environment so other code can ignore running during the data fetch

---

README.md

Clarify the use of `limit`

---

CHANGELOG.md
CONTRIBUTING.md
Gemfile
README.md
contentful_middleman.gemspec
lib/contentful_middleman/commands/contentful.rb
lib/contentful_middleman/core.rb
lib/contentful_middleman/instance.rb

Fixes #45 
Fixes #9 
From [instrument/contentful_middleman](https://github.com/Instrument/contentful_middleman)

Add method for getting all entries

---

CHANGELOG.md
README.md
lib/contentful_middleman/core.rb
lib/contentful_middleman/webhook_server.rb

This could be improved if https://github.com/middleman/middleman/issues/1624 is implemented

Add Webhook support

---

.travis.yml

Change Ruby versions on travis.yml to supported Ruby versions

---

CHANGELOG.md
README.md
lib/contentful_middleman/instance.rb

Clarify :all_entries ordering and provide sane default

---

CHANGELOG.md
lib/contentful_middleman/mappers/base.rb
spec/contentful_middleman/mappers/base_spec.rb
spec/spec_helper.rb

Fix error on empty entry

---

lib/contentful_middleman/mappers/base.rb
spec/contentful_middleman/mappers/base_spec.rb

Please backport this feature in `middleman-v3-stable` branch

Add asset.description in map_asset

---

CHANGELOG.md
lib/contentful_middleman/mappers/base.rb
spec/contentful_middleman/mappers/base_spec.rb
spec/fixtures/vcr_fixtures/entries/nil_file.yml

Related to #85 
Related to contentful/contentful.rb#95

Fix error when asset file is nil

---

CHANGELOG.md
README.md
contentful_middleman.gemspec
lib/contentful_middleman/core.rb
lib/contentful_middleman/instance.rb
spec/contentful_middleman/instance_spec.rb
spec/fixtures/vcr_fixtures/instance/entries_3.yml
spec/spec_helper.rb

Add Page Size Options

---

CHANGELOG.md
lib/contentful_middleman/commands/context.rb
lib/contentful_middleman/mappers/base.rb
spec/contentful_middleman/mappers/base_spec.rb
spec/fixtures/vcr_fixtures/entries/localized_references.yml

Depends on https://github.com/contentful/contentful.rb/pull/106
Fixes #95

Fix Link resolution on localized content

---

CHANGELOG.md
lib/contentful_middleman/commands/context.rb
lib/contentful_middleman/mappers/base.rb
spec/contentful_middleman/mappers/base_spec.rb
spec/fixtures/vcr_fixtures/entries/localized_references_localized_assets.yml

Fix localized resource serialization for localized Assets

---

CHANGELOG.md
lib/contentful_middleman/mappers/base.rb
spec/contentful_middleman/mappers/base_spec.rb
spec/fixtures/vcr_fixtures/entries/repeated_entry.yml

Fix repeated entries on reference arrays

---

.travis.yml
CHANGELOG.md
Gemfile
README.md
contentful_middleman.gemspec
lib/contentful_middleman/commands/context.rb
lib/contentful_middleman/core.rb
lib/contentful_middleman/instance.rb
lib/contentful_middleman/mappers/base.rb
lib/contentful_middleman/tools/preview_proxy.rb
lib/contentful_middleman/version.rb
spec/contentful_middleman/core_spec.rb
spec/contentful_middleman/instance_spec.rb
spec/contentful_middleman/mappers/base_spec.rb
spec/fixtures/vcr_fixtures/entries/localized_references.yml
spec/fixtures/vcr_fixtures/entries/localized_references_localized_assets.yml
spec/fixtures/vcr_fixtures/entries/nil_file.yml
spec/fixtures/vcr_fixtures/entries/repeated_entry.yml
spec/fixtures/vcr_fixtures/helpers/preview.yml
spec/fixtures/vcr_fixtures/instance/entries_3.yml
spec/fixtures/vcr_fixtures/tools/preview_helper.yml
spec/fixtures/vcr_fixtures/tools/preview_helper/asset.yml
spec/fixtures/vcr_fixtures/tools/preview_helper/asset_2.yml
spec/fixtures/vcr_fixtures/tools/preview_helper/assets.yml
spec/fixtures/vcr_fixtures/tools/preview_helper/assets_2.yml
spec/fixtures/vcr_fixtures/tools/preview_helper/entries.yml
spec/fixtures/vcr_fixtures/tools/preview_helper/entries_2.yml
spec/fixtures/vcr_fixtures/tools/preview_helper/entry.yml
spec/fixtures/vcr_fixtures/tools/preview_helper/entry_2.yml
spec/spec_helper.rb

I just merged `master` into `dl/upgrade-to-v4` and resolved merge conflicts, but I didn't do a super thorough job (nor do I understand all the changes that were made). ~~I'd like to run the tests, but I'm not sure how to do so.~~
Edit: I now see that CI runs them. On it.

Update MM v4 branch to 1.5.0

---

CHANGELOG.md
Gemfile
contentful_middleman.gemspec
lib/contentful_middleman/mappers/base.rb
lib/contentful_middleman/tools/preview_proxy.rb
spec/contentful_middleman/mappers/base_spec.rb
spec/contentful_middleman/tools/preview_proxy_spec.rb
spec/fixtures/vcr_fixtures/tools/preview_helper.yml
spec/fixtures/vcr_fixtures/tools/preview_helper/asset.yml
spec/fixtures/vcr_fixtures/tools/preview_helper/asset_2.yml
spec/fixtures/vcr_fixtures/tools/preview_helper/assets.yml
spec/fixtures/vcr_fixtures/tools/preview_helper/assets_2.yml
spec/fixtures/vcr_fixtures/tools/preview_helper/entries.yml
spec/fixtures/vcr_fixtures/tools/preview_helper/entries_2.yml
spec/fixtures/vcr_fixtures/tools/preview_helper/entry.yml
spec/fixtures/vcr_fixtures/tools/preview_helper/entry_2.yml
spec/spec_helper.rb

Fixes #116 
Fixes #113 
Fixes #103 
Fixes #117 
Fixes #93

Upgrade to CDA 2.0.1 & Add `_meta`

---

DEPLOYING.md

@dlitvakb My apologize for taking so long to get to this.  Here's my first attempt.  Please poke at for improvements.  Perhaps some screen shots may be helpful.  Looking forward to your thoughts.

[add] netlify deploy

---

lib/contentful_middleman/helpers.rb
spec/contentful_middleman/helpers_spec.rb

fix that implements my proposed solution in #124

implemented fix for issue 124 / localize_entry

---

CHANGELOG.md
README.md
lib/contentful_middleman/commands/contentful.rb
lib/contentful_middleman/core.rb
spec/contentful_middleman/core_spec.rb

Add options to customize output path
